language: elixir
elixir:
  - 1.5.3
  - 1.6.6
  - 1.7.0
  - 1.7.2
otp_release:
  - 19.2
  - 20.0
  - 21.0
matrix:
  exclude:
    - elixir: 1.5.3
      otp_release: 21.0
    - elixir: 1.6.0
      otp_release: 21.0

sudo: false
script:
  - mix test
  - mix espec
  - mix espec spec_formatters/test_spec.exs
notifications:
  recipients:
    - anton.mishchuk@gmail.com
